blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import ListView, DetailView
from blog.models import Post
from taggit.models import Tag
from blog.views import TagListView, PostsFeed, AtomPostsFeed, getSearchResults
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import PostSitemap, GaleriaSitemap, FlatpageSitemap

# Define sitemaps
sitemaps = {
    'posts': PostSitemap,
    'galeria': GaleriaSitemap,
    'pages': FlatpageSitemap
}

urlpatterns = [
    # Index
    url(r'^(?P<page>\d+)?/?$', ListView.as_view(
        model=Post,
        paginate_by=5,
        ),
        name='index'
        ),

    # Individual posts
    url(r'^(?P<pub_date__year>\d{4})/(?P<pub_date__month>\d{1,2})/(?P<slug>[a-zA-Z0-9-]+).html?$', DetailView.as_view(
        model=Post,
        ),
        name='post'
        ),

    # Tags
    url(r'^tag/(?P<slug>[a-zA-Z0-9-]+).html?$', TagListView.as_view(
        paginate_by=5,
        model=Tag,
        ),
        name='tag'
        ),

    # Post RSS feed
    url(r'^feeds/posts/$', PostsFeed()),

    # Post RSS Atom
    url(r'^atom/posts/$', AtomPostsFeed()),

    # Search posts
    url(r'^search', getSearchResults, name='search'),

    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
]

blogplus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
from blogplus.views import markdown_uploader
from fotogaleria import views
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Blog URLs
    url(r'', include('blog.urls', namespace="blog")),

    # Galeria URLs
    url(r'^galeria/', include('galeria.urls')),
    url(r'^photo/$', views.photo_galeria, name='photo_galeria'),
    # Draceditor
    url(r'^draceditor/', include('draceditor.urls')),
    url(r'^api/uploader/$', markdown_uploader, name='markdown_uploader_page'),

    # Flat pages
    url(r'', include('django.contrib.flatpages.urls')),

    # Robots.txt Humans.txt
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^humans\.txt/$', TemplateView.as_view(template_name='humans.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from taggit.managers import TaggableManager
from django.utils.text import slugify
from django.utils import timezone
from draceditor.models import DraceditorField
from django.db.models.signals import post_save
from django.core.cache import cache

class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name=u'Tytuł')
    image = models.ImageField(
            upload_to='post',
            null=True,
            blank=True,
            width_field = "width_field",
            height_field = "height_field", verbose_name=u'Foto Image')
    height_field = models.IntegerField(default=0, verbose_name=u'Wysokość')
    width_field = models.IntegerField(default=0, verbose_name=u'Szerokość')
    pub_date = models.DateTimeField(default=timezone.now, verbose_name=u'Data')
    text = DraceditorField(verbose_name=u'Treść')
    slug = models.SlugField(max_length=40, unique=True, verbose_name=u'Odnośnik')
    author = models.ForeignKey(User, verbose_name=u'Autor')
    site = models.ForeignKey(Site, verbose_name=u'Strona')
    tags = TaggableManager(verbose_name=u'Tag')    


    def get_absolute_url(self):
        return "/%s/%s/%s.html" % (self.pub_date.year, self.pub_date.month, self.slug)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-pub_date"]

# Define signals
def new_post(sender, instance, created, **kwargs):
    cache.clear()

# Set up signals
post_save.connect(new_post, sender=Post)

blog/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import get_object_or_404, render_to_response
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Q
from django.views.generic import ListView
from blog.models import Post
from taggit.models import Tag
from django.contrib.syndication.views import Feed
from django.utils.feedgenerator import Atom1Feed
from django.utils.encoding import force_str
from django.utils.safestring import mark_safe
import markdown2

class TagMixin(object):
    def get_context_data(self, **kwargs):
        context = super(TagMixin, self).get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

class TagListView(TagMixin, ListView):
    template_name = 'blog/tag_post_list.html'

    model = Post
    context_object_name = 'post'

    def get_queryset(self, **kwargs):
        return Post.objects.filter(tags__slug=self.kwargs.get('slug'))    

class PostsFeed(Feed):
    title = "RSS BlogPlus 24z.biz"
    description = "Latest Posts of BlogPlus 24z.biz"
    link = '/'

    def items(self):
        return Post.objects.order_by('-pub_date')

    def item_title(self, item):
        return item.title

    def item_description(self, item):
        extras = ["fenced-code-blocks"]
        content = mark_safe(markdown2.markdown(force_str(item.text),
                                               extras = extras))
        return content

class AtomPostsFeed(PostsFeed):
    feed_type = Atom1Feed
    subtitle = PostsFeed.description

def getSearchResults(request):
    """
    Search for a post by title or text
    """
    # Get the query data
    query = request.GET.get('q', '')
    page = request.GET.get('page', 1)

    # Query the database
    results = Post.objects.filter(Q(text__icontains=query) | Q(title__icontains=query))

    # Add pagination
    pages = Paginator(results, 5)

    # Get specified page
    try:
        returned_page = pages.page(page)
    except EmptyPage:
        returned_page = pages.page(pages.num_pages)

    # Display the search results
    return render_to_response('blog/search_post_list.html',
                              {'page_obj': returned_page,
                               'object_list': returned_page.object_list,
                               'search': query})

blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load taggit_templatetags2_tags %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="ROBOTS" content="ALL">
    <meta name="Copyright" content="24z.biz">
    <meta name="keywords" content="vestacp, python, django, centos, postgresql">
    <meta name="description" content="Personal Blog Zbigniew Czechowski">
    <meta name="author" content="Zbigniew Czechowski">
    <link href="/feeds/posts/" rel="alternate" type="application/rss+xml" title="24z.biz BlogPlus RSS Feed">
    <link href="/atom/posts/" rel="alternate" type="application/atom+xml" title="24z.biz BlogPlus ATOM Feed">
    <link rel="icon" href="{% static 'ico/favicon.ico' %}">
    <title>{% block title %}BlogPlus- 24z.biz - {{ flatpage.title }}{% endblock %}</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Theme CSS -->
    <link href="{% static 'css/blog.min.css' %}" rel="stylesheet">
    <!-- Pygments -->
    <link href="{% static 'css/code.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">BlogPlus</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:index' %}">Home</a>
                    </li>
		    <li>
			<a href="/galeria/">Galeria</a>
		    </li>	
                    {% load flatpages %}
                        {% get_flatpages as flatpages %}
                        {% for flatpage in flatpages %}
                        <li><a href="{{ flatpage.url }}">{{ flatpage.title }}</a></li>
                        {% endfor %}
                </ul>
            </div>
		<div id="navbar" class="navbar-collapse collapse">
	          <form class="navbar-form navbar-right" action="/search" method="GET">
            <div class="form-group">
              <input type="text" name="q" placeholder="Search..." class="form-control">
            </div>
          </form>

        </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>BlogPlus</h1>
                        <hr class="small">
                        <span class="subheading">BlogPlus Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
	<div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
		{% block content %}{% endblock %}
                </div>
                <hr>
                <div class="post-preview">
                        <h2 class="post-title">
                            Tag Clound
                        </h2>
			{% get_tagcloud as tags %}
                        {% for tag in tags %}
                        <a href="/tag/{{ tag.slug }}.html"><font size={{tag.weight|floatformat:0}}>{{ tag }}</font></a>
                        {% endfor %}
                </div>
                <hr>
            </div>
        </div>
    </div>
    <hr>
    {% include "blog/footer.html" %}
    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
</body>
</html>

blog/templates/blog/base2.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load taggit_templatetags2_tags %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="ROBOTS" content="ALL">
    <meta name="Copyright" content="24z.biz">
    <meta name="keywords" content="vestacp, python, django, centos, postgresql">
    <meta name="description" content="Personal Blog Zbigniew Czechowski">
    <meta name="author" content="Zbigniew Czechowski">
    <link href="/feeds/posts/" rel="alternate" type="application/rss+xml" title="24z.biz BlogPlus $
    <link href="/atom/posts/" rel="alternate" type="application/atom+xml" title="24z.biz BlogPlus $
    <link rel="icon" href="{% static 'ico/favicon.ico' %}">
    <title>{% block title %}BlogPlus- 24z.biz - {{ flatpage.title }}{% endblock %}</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Theme CSS -->
    <link href="{% static 'css/blog.min.css' %}" rel="stylesheet">
    <!-- Pygments -->
    <link href="{% static 'css/code.css' %}" rel="stylesheet">
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-custom navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}">BlogPlus</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{% url 'blog:index' %}">Home</a>
                    </li>	
		    <li>
                        <a href="/galeria/">Galeria</a>
                    </li>	
                    {% load flatpages %}
                        {% get_flatpages as flatpages %}
                        {% for flatpage in flatpages %}
                        <li><a href="{{ flatpage.url }}">{{ flatpage.title }}</a></li>
                        {% endfor %}
                </ul>
            </div>
		<div id="navbar" class="navbar-collapse collapse">
	          <form class="navbar-form navbar-right" action="/search" method="GET">
            <div class="form-group">
              <input type="text" name="q" placeholder="Search..." class="form-control">
            </div>
            </form>
        </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>BlogPlus</h1>
                        <hr class="small">
                        <span class="subheading">BlogPlus Theme by Start Bootstrap</span>
                    </div>
                </div>
            </div>
        </div>
    </header>
	<div id="fb-root"></div>
        <script>(function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/pl_PL/all.js#xfbml=1";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));</script>
    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="post-preview">
		{% block content %}{% endblock %}
                </div>
                <hr>
            </div>
        </div>
    </div>
    <hr>
    {% include "blog/footer.html" %}
    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js' %}"></script>
</body>
</html>

blog/templates/blog/footer.html
<!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="/feeds/posts/" rel="alternate" type="application/rss+xml" title="24z.biz BlogPlus RSS Feed">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-feed fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="/sitemap.xml">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-sitemap fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
		   <p class="copyright text-muted">Copyright &copy; <a href="{% url 'blog:index' %}">24z.biz</a> {% now "Y" %}</p>
                </div>
            </div>
        </div>
    </footer>

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %}
{% load custom_markdown %}
{% block content %}
        <h2 class="post-title">{{ object.title }}</h2>
	<p class="post-meta">Posted on {{ post.pub_date|date:"M d, Y" }}&nbsp;
            &nbsp;Tag :&nbsp;
            {% if object.tags %}
            {% for tag in object.tags.all %}
            <a href="/tag/{{ tag.slug }}.html">{{ tag.name }}</a>
            {% endfor %}
	    {% endif %}	
        </p>
	<p>
	{% if object.image %}
                  <img class="img-responsive" src="{{ object.image.url }}"/>
	{% endif %}
	</p>
        {{ object.text|custom_markdown|linebreaks }}
	<p><div class="fb-like" data-href="https://{{ object.site }}{{ object.get_absolute_url }}" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div></p>
	<hr>
	<h2 class="post-title">Komentarze</h3><hr>
        <div class="fb-comments" data-href="http://{{ object.site }}{{ object.get_absolute_url }}" data-width="470" data-num-posts="10"></div>

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}
{% load custom_markdown %}
{% block content %}
        {% if object_list %}
            {% for post in object_list %}
	    <a href="{{ post.get_absolute_url }}">
            <h2 class="post-title">{{ post.title }}</h2></a>
            <p class="post-meta">Posted on {{ post.pub_date|date:"M d, Y" }}&nbsp;
            &nbsp;Tag :&nbsp;
	    {% if post.tags %}
            {% for tag in post.tags.all %}
            <a href="/tag/{{ tag.slug }}.html">{{ tag.name }}</a>
            {% endfor %}
            </p>
	    {{ post.text|custom_markdown|linebreaks|truncatechars:240 }}
            <hr>
	    {% endif %}
            {% endfor %}
	    	    	
        {% else %}
            <h2 class="post-title">No posts found</h2>
        {% endif %}

        <ul class="pager">
        {% if page_obj.has_previous %}
        <li class="previous"><a href="/{{ page_obj.previous_page_number }}/">Previous Page</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="next"><a href="/{{ page_obj.next_page_number }}/">Next Page</a></li>
        {% endif %}
        </ul>

    {% endblock %}

blog/templates/blog/search_post_list.html
{% extends "blog/base.html" %}
{% load custom_markdown %}
{% block content %}
	{% if object_list %}
            {% for post in object_list %}
            <h2 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p class="post-meta">Posted on {{ post.pub_date|date:"M d, Y" }}&nbsp;
            &nbsp;Tag :&nbsp;
            {% if post.tags %}
            {% for tag in post.tags.all %}
            <a href="/tag/{{ tag.slug }}.html">{{ tag.name }}</a>
            {% endfor %}
            </p>
            <hr>


            {{ post.text|custom_markdown|linebreaks }}

            {% endif %}
            {% endfor %}

        {% else %}
            <h2 class="post-title">No posts found</h2>
        {% endif %}

        <ul class="pager">
        {% if page_obj.has_previous %}
        <li class="previous"><a href="{% url 'blog:search' %}?page={{ page_obj.previous_page_number }}&q={{ search }}">Previous Page</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="next"><a href="{% url 'blog:search' %}?page={{ page_obj.next_page_number }}&q={{ search }}">Next Page</a></li>
        {% endif %}
        </ul>

    {% endblock %}

blog/templates/blog/sidebar.html
{% load taggit_templatetags2_tags %}
		<div class="well">
                    <h4>About this site</h4>
                    <p>This site is running Python 3.4.4 and the LTS version of Django.</p>
                </div>
                <div class="well">
                        <h4>Tag Cloud</h4>
                        {% get_tagcloud as tags %}
                        {% for tag in tags %}
                        <a href="/tag/{{ tag.slug }}.html"><font size={{tag.weight|floatformat:0}}>{{ tag }}</font></a>
                        {% endfor %}
                </div>

	    <div class="well">
                    <h4>Social Links</h4>
			<p><a href="https://github.com/">GitHub</a></p>
                </div>
		
		<div class="well">
                    <h4>Recommend</h4>
			<p><a href="https://mintshost.pl/start/?ref=239704">Mintshost</a></p>
                        <p><a href="https://panel.sldc.eu/aff.php?aff=228">Śląsk Data Center</a></p>
                </div>

blog/templates/blog/tag_post_list.html
{% extends "blog/base.html" %}
{% load custom_markdown %}
{% block content %}
        {% if object_list %}
            {% for post in object_list %}
            <h2 class="post-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
            <p class="post-meta">Posted on {{ post.pub_date|date:"M d, Y" }}&nbsp;
            &nbsp;Tag :&nbsp;
	    {% if post.tags %}
            {% for tag in post.tags.all %}
            <a href="/tag/{{ tag.slug }}.html">{{ tag.name }}</a>
            {% endfor %}
            </p>
            {{ post.text|custom_markdown|linebreaks }}
            <hr>
            {% endif %}
            {% endfor %}
	    	
        {% else %}
            <h2 class="post-title">No posts found</h2>
        {% endif %}

        <ul class="pager">
        {% if page_obj.has_previous %}
        <li class="previous"><a href="/{{ page_obj.previous_page_number }}/">Previous Page</a></li>
        {% endif %}
        {% if page_obj.has_next %}
        <li class="next"><a href="/{{ page_obj.next_page_number }}/">Next Page</a></li>
        {% endif %}
        </ul>

    {% endblock %}