blog/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import ListView, DetailView
from blog.models import Post
from taggit.models import Tag
from blog.views import TagListView, PostsFeed, AtomPostsFeed, getSearchResults
from django.contrib.sitemaps.views import sitemap
from blog.sitemap import PostSitemap, GaleriaSitemap, FlatpageSitemap

# Define sitemaps
sitemaps = {
    'posts': PostSitemap,
    'galeria': GaleriaSitemap,
    'pages': FlatpageSitemap
}

urlpatterns = [
    # Index
    url(r'^(?P<page>\d+)?/?$', ListView.as_view(
        model=Post,
        paginate_by=5,
        ),
        name='index'
        ),

    # Individual posts
    url(r'^(?P<pub_date__year>\d{4})/(?P<pub_date__month>\d{1,2})/(?P<slug>[a-zA-Z0-9-]+).html?$', DetailView.as_view(
        model=Post,
        ),
        name='post'
        ),

    # Tags
    url(r'^tag/(?P<slug>[a-zA-Z0-9-]+).html?$', TagListView.as_view(
        paginate_by=5,
        model=Tag,
        ),
        name='tag'
        ),

    # Post RSS feed
    url(r'^feeds/posts/$', PostsFeed()),

    # Post RSS Atom
    url(r'^atom/posts/$', AtomPostsFeed()),

    # Search posts
    url(r'^search', getSearchResults, name='search'),

    # Sitemap
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
            name='django.contrib.sitemaps.views.sitemap'),
]

blogplus/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.views.generic.base import TemplateView
from django.contrib import admin
from blogplus.views import markdown_uploader
from fotogaleria import views
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Blog URLs
    url(r'', include('blog.urls', namespace="blog")),

    # Galeria URLs
    url(r'^galeria/', include('galeria.urls')),
    url(r'^photo/$', views.photo_galeria, name='photo_galeria'),
    # Draceditor
    url(r'^draceditor/', include('draceditor.urls')),
    url(r'^api/uploader/$', markdown_uploader, name='markdown_uploader_page'),

    # Flat pages
    url(r'', include('django.contrib.flatpages.urls')),

    # Robots.txt Humans.txt
    url(r'^robots\.txt/$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
    url(r'^humans\.txt/$', TemplateView.as_view(template_name='humans.txt', content_type='text/plain')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

galeria/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from galeria import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^list/$', views.ListView.as_view(), name='galeria_list'),
    url(r'^(?P<pk>\d+)/$', views.GaleriaDetailView.as_view(), name='galeria_detail'),
    url(r'^foto/(?P<pk>\d+)/$', views.FotoDetailView.as_view(), name='foto_detail'),
]

galeria/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.db.models import permalink

from blogplus.fields import ThumbnailImageField

class Galeria(models.Model):
	name=models.CharField(max_length=250, verbose_name=u'Nazwa')
	pub_date = models.DateTimeField(default=timezone.now, verbose_name=u'Data')
	description=models.TextField(verbose_name=u'Opis')

	class Meta:
		ordering=['name']

	def __str__(self):
		return self.name

	@permalink
	def get_absolute_url(self):
		return ('galeria_detail',None,{'pk':self.id})

class Foto(models.Model):
	galeria=models.ForeignKey(Galeria)
	title=models.CharField(max_length=100, verbose_name=u'Tytuł')
	image=ThumbnailImageField(upload_to='foto')
	caption=models.CharField(max_length=250,blank=True, verbose_name=u'Podpis')

	class Meta:
		ordering=['title']

	def __str__(self):
		return self.title

	@permalink
	def get_absolute_url(self):
		return ('foto_detail',None,{'pk':self.id})

galeria/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.views import generic
from galeria.models import Galeria, Foto
        
class IndexView(generic.ListView):
    template_name = 'galeria/index.html'
    def get_queryset(self):
        return Galeria.objects.all()[:5]
        
class ListView(generic.ListView):
    model = Galeria
    template_name = 'galeria/galeria_list.html'
        
class GaleriaDetailView(generic.DetailView):
    model = Galeria
    template_name = 'galeria/galeria_detail.html'
        
class FotoDetailView(generic.DetailView):
    model = Foto
    template_name = 'galeria/foto_detail.html'

galeria/templates/galeria/foto_detail.html
{% extends "blog/base2.html" %}
{% block content %}
<a href="{{ object.galeria.get_absolute_url }}">
<h2 class="post-title">
{{ object.galeria.name }}</h2></a>
<p>{{ object.galeria.name }} - {{ object.title }}</p>
<img class="img-responsive" src="{{ object.image.url}}">
{% if object.caption %}
<p>{{ object.caption }}</p>
{% endif %}
<ul class="pager">
<li class="next">
<a href="{% url 'galeria_list'  %}">Lista Galerii &rarr;</a>
</li>
</ul>
{% endblock %}

galeria/templates/galeria/galeria_detail.html
{% extends "blog/base2.html" %}
{% block content %}
<h2 class="post-title">{{ object.name }}</h2>
<p>{{ object.description }}</p>
{% for foto in object.foto_set.all %}
<p>{{ photo.title }}</p>
<a href="{{ foto.get_absolute_url }}">
<img class="img-responsive" src="{{ foto.image.thumb_url }}"></a>
<p>{{ photo.caption }}</p>
{% endfor %}
<ul class="pager">
<li class="next">
<a href="{% url 'galeria_list'  %}">Lista Galerii &rarr;</a>
</li>
</ul>
{% endblock %}

galeria/templates/galeria/galeria_list.html
{% extends "blog/base2.html" %}
{% block content %}
{% for galeria in object_list %}
<a href="{{ galeria.get_absolute_url }}">
<h2 class="post-title">{{ galeria.name }}</h2></a>
{% if galeria.foto_set.count %}
<p><img class="img-responsive" src="{{ galeria.foto_set.all.0.image.thumb_url }}"></p><hr>
{% else %}
<p>No Foto</p>
{% endif %}
{% endfor %}
<ul class="pager">
<li class="next">
<a href="{% url 'galeria_list'  %}">Lista Galerii &rarr;</a>
</li>
</ul>
{% endblock %}

galeria/templates/galeria/index.html
{% extends "blog/base2.html" %}
{% block content %}
{% for galeria in object_list %}
<a href="{{ galeria.get_absolute_url }}">
<h2 class="post-title">{{ galeria.name }}</h2></a>
{% if galeria.foto_set.count %}
<p><img class="img-responsive" src="{{ galeria.foto_set.all.0.image.thumb_url }}"></p><hr>
{% else %}
<p>No Foto</p>
{% endif %}
{% endfor %}
<ul class="pager">
<li class="next">
<a href="{% url 'galeria_list'  %}">Lista Galerii &rarr;</a>
</li>
</ul>
{% endblock %}